# Generated by Django 4.1 on 2024-04-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='start_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
