# Generated by Django 4.1 on 2024-04-05 08:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0004_transaction_approved"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="end_at",
            new_name="approved_at",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="approved",
            new_name="finished",
        ),
    ]
