# Generated by Django 4.1 on 2024-04-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0005_rename_end_at_transaction_approved_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="device_id",
            field=models.IntegerField(default=0),
        ),
    ]
